# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np
import numpy.random as rand

# Чтобы нормализовать значения между 0 и 1, мы можем использовать следующую формулу:
# 
# x норма = (x i – x мин ) / (x макс – x мин )
mas = np.random.randint(0, 20, (4, 7))
print(mas, '\n')
x_min = np.min(mas)
x_max = np.max(mas)

normalized_mas = (mas - x_min) / (x_max - x_min)
print('Normalized data:\n\n',normalized_mas)


[[ 8  2 18  8  3 16 19]
 [ 5  2  2  3 14 18 11]
 [14 11 17  0  6  9  3]
 [ 1  9 15  2 12  8 15]] 

Normalized data:

 [[0.42105263 0.10526316 0.94736842 0.42105263 0.15789474 0.84210526
  1.        ]
 [0.26315789 0.10526316 0.10526316 0.15789474 0.73684211 0.94736842
  0.57894737]
 [0.73684211 0.57894737 0.89473684 0.         0.31578947 0.47368421
  0.15789474]
 [0.05263158 0.47368421 0.78947368 0.10526316 0.63157895 0.42105263
  0.78947368]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [2]:
matr = np.random.randint(0, 10, (8, 10))
mn = matr[1, :]
ind=0
print(matr, end = '\n\n')
for i in matr:
    if np.sum(i) < np.sum(mn):
        mn = i
    print(np.sum(i), end = ' ')
mn_ind = np.where(np.sum(matr, axis=1) == np.sum(mn))
print()

print(f'\n Минимальная сумма: {np.sum(mn)} \n Строка в массиве: {mn_ind[0][0] + 1}')



[[1 1 6 8 3 6 0 1 0 4]
 [9 3 3 9 4 2 0 8 6 1]
 [0 2 9 7 1 0 5 1 9 7]
 [0 5 3 9 0 0 5 1 3 6]
 [7 0 8 9 8 9 4 0 0 8]
 [4 6 1 4 5 0 8 7 2 9]
 [3 2 2 2 3 9 3 7 3 5]
 [7 0 4 5 0 7 6 0 9 3]]

30 45 41 32 53 46 39 41 

 Минимальная сумма: 30 
 Строка в массиве: 1


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [3]:
point_1 = np.array((0, 0, 0))
point_2 = np.array((3, 3, 3))
sm = np.sqrt((point_2[0] - point_1[0])**2 + (point_2[1] - point_1[1])**2 + (point_2[2] - point_1[2]) ** 2)
print(sm)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [4]:
#A*X*B=-C
a=np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b=np.array([[3, -1], [2, 1]])
c=-np.array([[7, 21], [11, 8], [8, 4]])

#X= A**-1 * -C * B**-1
res = np.linalg.inv(a) @ c @ np.linalg.inv(b)
print(res)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [29]:
file = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype='int32', skiprows=1)
print(file[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [82]:
print(f'2 столбец|\nМинимум: {np.min(file[:, 1])}\nМаксимум: {np.max(file[:, 1])}\nМедиана: {np.median(file[:, 1])}\n')
print(f'3 столбец|\nМинимум: {np.min(file[:, 2])}\nМаксимум: {np.max(file[:, 2])}\nМедиана: {np.median(file[:, 2])}\n')

2 столбец|
Минимум: 0
Максимум: 2147483647
Медиана: 40.0

3 столбец|
Минимум: 1
Максимум: 39
Медиана: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [127]:
# Квантиль - это показатель, который разделяет упорядоченную выборку на равные части. Например, медиана - это 50-й процентиль, то есть значение, которое делит выборку на две равные части. Квантиль 25% - это значение, которое делит выборку на две части, где 25% значений находятся ниже этого значения, а 75% значений находятся выше.
time = np.array(file[:, 1])
q = np.quantile(time, 0.75)
time = time[time <= q]
time = time.reshape(-1, 1)
print(time)

[[60]
 [25]
 [10]
 ...
 [35]
 [65]
 [ 5]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [142]:
column = np.array(file[:, 1])
zeros = column[column == 0]
print(f'Для {len(zeros)} рецептов продолжительность равна нулю')

mask = column == 0 #создаем булеву маску
mask = np.array(mask)
column[mask] = 1

print(f'После замены:{column}')
zeros = column[column == 0]
print(f'Для {len(zeros)} рецептов продолжительность равна нулю')

Для 479 рецептов продолжительность равна нулю
После замены:[ 60  25  10 ...  65   5 140]
Для 0 рецептов продолжительность равна нулю


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [151]:
print(f'В датасете {np.unique(file[:, 0]).size} уникальных рецептов')

В датасете 100000 уникальных рецептов


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [153]:
print(f'В датасете {np.unique(file[:, 2]).size} уникальных значений')
print(f'Значения: {np.unique(file[:, 2])}')

В датасете 37 уникальных значений
Значения: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [164]:
file_1 = file.copy()
mask = file_1[:, 2] <= 5
file_1 = file_1[mask]
print(file_1)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [173]:
mask = file[:, 1] != 0
file = file[mask]
res = file[:, 2] / file[:, 1]
print(f'В среднем на 1 минуту: {res} \nМаксимальное: {np.max(res)}')

В среднем на 1 минуту: [0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ] 
Максимальное: 23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [185]:
file_sorted = file[np.argsort(file[:, 1])][::-1] #сортировка по возрастанию
top = file_sorted[:100]
ingr = top[:, 2]
print(np.sum(ingr)/(ingr).size)

6.63


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [193]:
indx = np.random.randint(0, len(file), 10)
print(file[indx])

[[286429     30     11]
 [ 78173     23     13]
 [ 14323     40      9]
 [200730     35      3]
 [123976     50      9]
 [214610     25      7]
 [195085    215     12]
 [352662     65     15]
 [382613     27     12]
 [145339     65     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [199]:
ingr = file[:, 2]
sr = np.median(ingr) #среднее
mask = ingr < sr #булева маска для поиска меньше среднего
ingr_lower = ingr[mask]
res = (ingr_lower.size / ingr.size) * 100 # процент
print(res)

48.19887259975282


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [252]:
file = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype='int32', skiprows=1)
mask = (file[:, 1] <= 20) & (file[:, 2] <= 5)
flag = np.arange(len(file)).reshape(-1, 1)
flag[mask] = 1
flag[~mask] = 0
flag
file_new = np.concatenate((file, flag), axis=1 )
print(file_new)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [265]:
al = len(file_new)
temp = np.array(file_new[:, 3])
simple = temp[temp == 1]
res = len(simple) / al
print(res)

0.09552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.